### ISSUE TITLE
Some tiles fail to load when rotating, panning, and rotating back to 0

### ISSUE THREAD

**Issue by fnicollet** [hyperknot/Leaflet#2]
Here is how to reproduce this issue with map.html
Zoom 5x, click 45°:
![image](https://cloud.githubusercontent.com/assets/1240481/16101262/672ab6ec-3364-11e6-8992-37256908977e.png)
Pan to the right:
![image](https://cloud.githubusercontent.com/assets/1240481/16101267/7861b7bc-3364-11e6-93b2-66323e0066e1.png)
Go back to rotation 0 and pan around. The borders of the map won't be filled with tiles:
![image](https://cloud.githubusercontent.com/assets/1240481/16101300/bf7200a8-3364-11e6-9028-8047b2a19833.png)

My guess is that it comes from tests like this in Map.js:
https://github.com/hyperknot/Leaflet/blob/rotate-rc1/src/map/Map.js#L668

it tests for 
```
if (this._rotate && this._bearing) {
```
Which will return false if bearing is at 0° and do the usual behaviour of the function. 
If I remove the test in _getNewPixelOrigin:
https://github.com/hyperknot/Leaflet/blob/rotate-rc1/src/map/Map.js#L1165
 and just keep if (this._rotate), I cannot reproduce the bug anymore.

I am not sure if the two other bearing tests should be dropped as well

**Comment by fnicollet** [comment]
After a few more tests, the other 2 tests should drop the test on bearing as well, otherwise you get other issues if you reproduce this issue and then zoom in and out

**Comment by hyperknot** [comment]
@fnicollet thanks for the issue, this is exactly the bug I'm trying to fix. Can you try testing removing those lines? The project in the debug dir don't need building Leaflet, they work out of the box.

**Comment by fnicollet** [comment]
Tried it, it seems to fix the issue :) Can you give it a go ? maybe tomorrow as it must be rather late for you as well ahah

**Comment by hyperknot** [comment]
Should be fixed with #4.
