### ISSUE TITLE
Popups should not be rotated

### ISSUE THREAD

**Issue by fnicollet** [hyperknot/Leaflet#3]
At the moment,the popup-pane is not counter-rotated, so it rotates with the map, which renders the texts unreadable:
![image](https://cloud.githubusercontent.com/assets/1240481/16101595/6b32ae68-3367-11e6-8a81-a2a6c7733ce0.png)

They should remain straight, like markers. The code should be along those lines:
https://github.com/hyperknot/Leaflet/commit/c26a3fb82a406f08b85e69642881d6b5b272bbe9

**Comment by hyperknot** [comment]
Now this one has to be developed from scratch, even if it is similar as you've linked.

**Comment by hyperknot** [comment]
I put comment here, since I had to revert #23 and it got closed:
Couple of bugs:

1. Try open popup and then rotate the map, popup will rotate
2. Sometimes (I have no idea what makes a difference, almost randomly), popups open in totally different spaces, rotated, like:
![image](https://cloud.githubusercontent.com/assets/494223/16401723/090a3448-3ce7-11e6-969d-9cd142341b34.png)
3. The PR not mergable after https://github.com/Leaflet/Leaflet/commit/01790eacda23fe0b33f43c0b8ecdbdced9d27df5 (this one is super fresh). Please rebase on the new version.

**Comment by hyperknot** [comment]
Also, @wellenvogel made a custom solution where popups rotate perfectly, I'd be curious to see how he did it.
https://github.com/Leaflet/Leaflet/issues/268#issuecomment-228601468

**Comment by fnicollet** [comment]
Not really perfect :) seems like he didn't fix the animateZoom function so the popup goes weird when map is rotated and you zoom in and out
My code used to work well in all situation, might be related to other PR that got merged, i'll try to rebase with leaflet current master and fix it

**Comment by hyperknot** [comment]
@fnicollet I run into the bug in your original branch, this new one is just a merge conflict, I couldn't even try it on it.

**Comment by wellenvogel** [comment]
My rotation stuff for popups is currently more like a hack. The source link is in the example. Just did the rotation on a couple of events . Does still not work for panZoom altough this could be added.

**Comment by hyperknot** [comment]
@wellenvogel have a look at our code and see if you'd like to join contributing to it! This one is a hack too, but we try to make it as elegant as possible.

**Comment by hyperknot** [comment]
Let's have a look at how does it go after #25.

**Comment by hyperknot** [comment]
Steps to reproduce the popup bug:
1. open rotate.html
2. click 45
3. click on this marker:
![image](https://cloud.githubusercontent.com/assets/494223/16432190/35eb33ac-3d84-11e6-90ac-b0cbb1375f64.png)
-> popup opens far away

Works the same in Chrome and FF.

**Comment by fnicollet** [comment]
I see, I can reproduce it, _containerLeft is undefined when things are happening in that order, I am going to find out why

**Comment by fnicollet** [comment]
Not sure if opening a PR was the best move in terms of history management but also wasn't sure if you   could modify a PR once it has been merged

**Comment by hyperknot** [comment]
Yes, it is the only option after a PR is closed.

**Comment by hyperknot** [comment]
OK, almost done now!

Tiny edge case is zoomAnimation: false with rotation, but we can even put it to known issues.
