### ISSUE TITLE
Backport touch gestures and merge in this branch

### ISSUE THREAD

**Issue by fnicollet** [hyperknot/Leaflet#6]
Do you think you could cherry pick the other commits related to touch interaction from @IvanSanchez branch and merge it with your rotate-rc1 branch?

**Comment by hyperknot** [comment]
@fnicollet it is not possible to cherry pick any commits. There has been thousands of commits since then. The only way is to manually implement those changes, looking at the original branch as a reference.

I personally don't need to use the touch gestures at all, so feel free to implement them and make PRs.

**Comment by fnicollet** [comment]
ok, will try to do that tonight. need to learn how to squash commits again
though, wish there was a way in github ahah

On Fri, Jun 17, 2016 at 2:07 PM, Zsolt Ero <notifications@github.com> wrote:

> @fnicollet <https://github.com/fnicollet> it is not possible to cherry
> pick any commits. There has been thousands of commits since then. The only
> way is to manually implement those changes, looking at the original branch
> as a reference.
>
> I personally don't need to use the touch gestures at all, so feel free to
> implement them and make PRs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperknot/Leaflet/issues/6#issuecomment-226752649>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABLtod-HLu7lHNgyk2zi4Eebe9ZzeE5mks5qMo4AgaJpZM4I4S3c>
> .
>



-- 
Fabien Nicollet
Tel : +33 (0)6 60 54 72 20

**Comment by hyperknot** [comment]
Don't worry about squash, GitHub can do it now!

**Comment by fnicollet** [comment]
I haven't been able to test this PR with all the other PR. I am not sure about the code where it doesn't dispatch the "rotate" event during touch move, it might mess up some of the other code like markers popup and such which are updated on rotate. Might be best throttling the touch move instead of having this logic.
Need to try it once you merged the rest of the PRs

**Comment by hyperknot** [comment]
@fnicollet do you need the touch gestures personally? They constantly break in "normal" Leaflet as well, adding the rotation one would make it way more likely to be buggy. 

If none of us need it we should wait with merging it.

**Comment by fnicollet** [comment]
I would merge them as it is quite practical for debugging as well (using
the slider is a bit annoying). They are not enabled by default so no harm
done by default :)
But it might make merges harder as the TouchZoom code has been moved to
TouchGestures while they are still in TouchZoom in master, so patches won't
apply well I guess.

I don't think I will need them right away, so this can wait

On Tue, Jun 21, 2016 at 3:35 PM, Zsolt Ero <notifications@github.com> wrote:

> @fnicollet <https://github.com/fnicollet> do you need the touch gestures
> personally? They constantly break in "normal" Leaflet as well, adding the
> rotation one would make it way more likely to be buggy.
>
> If none of us need it we should wait with merging it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperknot/Leaflet/issues/6#issuecomment-227441256>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABLtoUPCvJ7q1JQ_pcKKDSK9y1ckEhfeks5qN-ingaJpZM4I4S3c>
> .
>



-- 
Fabien Nicollet
Tel : +33 (0)6 60 54 72 20

**Comment by hyperknot** [comment]
If it's only for debugging, I would strongly recommend not merging them. Touch gestures make at least 80% of Leaflet's cross-platform cross-browser bugs, if we don't need it we shouldn't add it.

**Comment by fnicollet** [comment]
ok, works for me

On Tue, Jun 21, 2016 at 3:42 PM, Zsolt Ero <notifications@github.com> wrote:

> If it's only for debugging, I would strongly recommend not merging them.
> Touch gestures make at least 80% of Leaflet's cross-platform cross-browser
> bugs, if we don't need it we shouldn't add it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperknot/Leaflet/issues/6#issuecomment-227443148>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABLtoXLdpiFY9Ewx7XXVraSl4ZhU1I_xks5qN-o4gaJpZM4I4S3c>
> .
>



-- 
Fabien Nicollet
Tel : +33 (0)6 60 54 72 20

**Comment by hyperknot** [comment]
Closing this one and leaving the PR open.

**Comment by fnicollet** [comment]
I need to try it some more tonight but it seems that touch-zoom (without rotating or anything) is currently broken in rotate-rc1 when the map is rotated (the map pans to the location of the second touch). So it might be needed to actually merge the PR, just to fix touch zoom (touch rotate could be disabled by default)
Will investigate later

**Comment by hyperknot** [comment]
@fnicollet I agree, if that is the case then we might need to port over the needed changes.

**Comment by fnicollet** [comment]
The new PR is ready to be merged!
Leaflet master needs a fix but that's a separate issue that should resolve itself soon, see my comment in the PR
